DROP DATABASE IF EXISTS likes_db;

CREATE DATABASE likes_db;

CREATE TABLE films(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(30) NOT NULL
);

CREATE TABLE songs(
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(30) NOT NULL
);